jwt:
  filter:
    secret-key: $xurr00s
    public-resources:
      - method: POST
        urls: /user
      - method: GET
        urls: /swagger-ui.html, /swagger-resources/**, /v2/**, /webjars/**

server:
  port: 8080
  h2:
    console:
      enabled: true
