jwt:
  filter:
    secret-key: $xurr00s
    public-resources:
      - method: POST
        urls: /user,/user/login
      - method: GET
        urls: /swagger-ui.html, /swagger-resources/**, /v2/**, /webjars/**

app:
  token-expiration-minutes: 30

spring:
  jackson:
    default-property-inclusion: NON_NULL